always set the UID/GID of container so that it can be easily overriden
scientist-softserv/softserv-training-workshops-2023 pull request #5
Opened 2023-09-13 19:20 UTC by orangewolf

this allows for the linux folks to more easily deal with file permissions issues.

2023-09-13 21:08 UTC, jeremyf approved these changes

2023-09-14 18:34 UTC, alishaevn requested changes

2023-09-14 18:34 UTC, alishaevn commented on .env
> +DB_HOST=db
```suggestion
```

2023-09-14 18:34 UTC, alishaevn commented on .env
> +DB_HOST=db
duplication

2023-09-15 21:09 UTC, alishaevn approved these changes

2023-09-15 21:12 UTC, merged